### ISSUE TITLE
failing test case for small system

### ISSUE THREAD

**Issue by chu-k** [Adrian-Diaz/Temporary_CAC#51]
fdc424ce561b1b6d6c7bea251f93242ce0ec0230

Backtrace for CAC/fire min error in allocate_quad_neigh_list. Is there a minimum system size? 
![image](https://user-images.githubusercontent.com/3358071/59373981-a6882480-8cff-11e9-890e-2c2503ba466e.png)

**Comment by Adrian-Diaz** [comment]
It should work for those 4 atoms; something circuitous must be happening to leave somethin undefined at that point. Also is that the most recent build for that class? I cant make sense of the line number in the stack frame since its an empty line surrounded by comments for me. More than likely memory is corrupted by something earlier on given that there are ten frames deep into the malloc routine before segfault. Gonna have to valgrind that case to know why assuming its the latest version of the infrastructure.

**Comment by chu-k** [comment]
Yeah this was a fresh branch off master two commits back, just pulled the new changes as well. You were right about the dense vector index being incremented incorrectly. Valgrind would have caught it, but unfortunately it does not build correctly on OS X Mojave (work computer). Now fixing a velocity update issue.

**Comment by chu-k** [comment]
Was incrementing the dense_count_f index instead of the velocity index.
